{% set name = "jaraco.context" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaraco_context-{{ version }}.tar.gz
  sha256: 9bae4ea555cf0b14938dc0aee7c9f32ed303aa20a3b73e7dc80111628792d1b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
  run:
    - python >=3.8
    - backports.tarfile

test:
  imports:
    - jaraco.context

about:
  home: https://github.com/jaraco/jaraco.context
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Context managers by jaraco
  doc_url: https://jaracocontext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.context

extra:
  recipe-maintainers:
    - carlodri
