{% set name = "jaraco.context" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2f67165ce1f9be20f32f650f25d8edfc1646a8aeee48ae06fb35f90763576d2

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
  run:
    - python >={{ python_min }}
    - backports.tarfile

test:
  requires:
    - python {{ python_min }}
  imports:
    - jaraco.context

about:
  home: https://github.com/jaraco/jaraco.context
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Context managers by jaraco
  doc_url: https://jaracocontext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.context

extra:
  recipe-maintainers:
    - carlodri
